Improve Codecov coverage
PTsolvers/JustRelax.jl pull request #210
Opened 2024-08-08 12:57 UTC by aelligp

Improve the Codecov percentage of the pkg and fix a few copy paste bugs

2024-08-08 18:03 UTC, albert-de-montserrat requested changes

2024-08-08 18:03 UTC, albert-de-montserrat commented on src/common.jl
> +    @strain_plastic,
Would not be better to call it `@plastic_strain`?

2024-08-08 18:03 UTC, albert-de-montserrat commented on src/common.jl
> +    indices
I'm not sure about exporting these functions, as they are for internal use. What do you need them for?

2024-08-08 18:03 UTC, albert-de-montserrat commented on test/test_IO.jl
>          ni           = nx, ny     # number of cells
Should be `ni = nx, ny, nz` now

2024-08-08 18:03 UTC, albert-de-montserrat commented on test/test_IO.jl
> +        thermal = ThermalArrays(backend_JR,  (nx,ny,nz))
```suggestion
        stokes  = StokesArrays(backend_JR, ni)
        thermal = ThermalArrays(backend_JR, ni)
```

2024-08-08 18:03 UTC, albert-de-montserrat commented on test/test_Utils.jl
> +        @test detect_args_size(tuple_args) == (7, 5)
Instead of exporting `detect_args_size` (and the other newly exported functions), just import them as `import JustRelax2D : fun1, fun2, etc`

2024-08-12 08:38 UTC, aelligp commented on src/common.jl
> +    indices
True, I do it this way

2024-08-14 12:47 UTC, albert-de-montserrat commented on docs/src/man/subduction2D/setup.md
> +    Origin  = nothing, StrikeAngle=0, DipAngle=-30,
```suggestion
    Origin  = (nothing, StrikeAngle=0, DipAngle=-30),
```
I think the brackets are really needed here or it will crash.

2024-08-14 12:47 UTC, albert-de-montserrat commented on miniapps/convection/GlobalConvection2D_Upwind.jl
> +    # igg = IGG(init_global_grid(nx, ny, 1; init_MPI = JustRelax.MPI.Initialized() ? false : true)...)
```suggestion
```

2024-08-14 12:50 UTC, albert-de-montserrat commented on test/test_Interpolations.jl
> +        igg          = IGG(init_global_grid(nx, ny, 1; init_MPI= true)...)
```suggestion
```
We don't really need `igg` here, don't we?

2024-08-14 12:51 UTC, albert-de-montserrat commented on test/test_Interpolations.jl
> +        stokes.τ.xy_c      .= @fill(1.0)
```suggestion
        stokes.viscosity.η .= 1
        stokes.V.Vy        .= 10
        thermal.T          .= 100
        thermal.Told       .= 50
        stokes.τ.xy_c      .= 1
```

2024-08-14 12:53 UTC, albert-de-montserrat commented on test/test_Interpolations.jl
> +        @test stokes.τ.xy[2,2] == 1.0
```suggestion
        @test stokes.τ.xy[2,2] == 1
```

Double equality tests that both the left and right hand side **values** are equal, doesn't compare the types, so `== 1` is enough in this case.

If you want to test value **and** type then use triple equality instead.

2024-08-14 12:54 UTC, albert-de-montserrat commented on test/test_Interpolations.jl
> +        @test Vx_v[1,1] == 0.0
```suggestion
        @test iszero(Vx_v[1,1])
```

2024-08-14 12:54 UTC, albert-de-montserrat commented on test/test_Interpolations.jl
> +        @test Vy_v[1,1] == 10.0
```suggestion
        @test Vy_v[1,1] == 10
```

2024-08-14 12:54 UTC, albert-de-montserrat commented on test/test_Interpolations.jl
> +        @test Vy_v[1,1] == 10.0
```suggestion
        @test iszero(Vx_v[1,1])
        @test Vy_v[1,1] == 10
```

2024-08-14 12:56 UTC, albert-de-montserrat commented on test/test_traits.jl
> +        @test PTArray()        === A
```suggestion
        @test PTArray() === A
```

2024-08-14 13:18 UTC, aelligp commented on docs/src/man/subduction2D/setup.md
> +    Origin  = nothing, StrikeAngle=0, DipAngle=-30,
Apparently not as it was reported by @ChristianSchuler

2024-08-15 09:26 UTC, merged