Implementation of IGG to 2D stokes solvers
PTsolvers/JustRelax.jl pull request #39
Opened 2023-04-11 13:24 UTC by aelligp

- implements Implicit global grid to 2D solvers

- updates test and benchmarks

2023-04-13 13:54 UTC, albert-de-montserrat requested changes

2023-04-13 13:54 UTC, albert-de-montserrat commented on miniapps/benchmarks/stokes/solcx/SolCx.jl
> +            stokes, pt_stokes, di, flow_bcs, ρg, η, G, K, dt, igg::IGG;
remove `::IGG`

2023-04-13 13:54 UTC, albert-de-montserrat commented on miniapps/benchmarks/stokes/solcx/SolCx.jl
> +        @hide_communication b_width begin
I think `b_width` is not defined

2023-04-13 13:54 UTC, albert-de-montserrat commented on miniapps/benchmarks/stokes/solcx/SolCx.jl
> +    # di = @. li / ni # grid step in x- and -y
remove these comented lines

2023-04-13 13:54 UTC, albert-de-montserrat commented on miniapps/benchmarks/stokes/solkz/SolKz.jl
> +    # di = @. li / ni # grid step in x- and -y
remove thse comented lines

2023-04-13 13:54 UTC, albert-de-montserrat commented on miniapps/benchmarks/stokes/solvi/SolVi.jl
> +
remove thse comented lines

2023-04-13 13:54 UTC, albert-de-montserrat commented on miniapps/benchmarks/stokes/solvi/SolViEl.jl
> +
remove these comented lines

2023-04-14 15:12 UTC, aelligp commented
3D benchmarks need revision due to boundary conditions - otherwise IGG implementation is done

2023-04-15 08:30 UTC, albert-de-montserrat reviewed
I think that [here](https://github.com/PTsolvers/JustRelax.jl/blob/ad19be269569a941ce925d4c2ba09f9bd22f6546/miniapps/benchmarks/stokes/solcx/SolCx.jl#L16) - and probably in some of the other benchmarks- you need to create the coordinate array using `x_g` / ''y_g' from [`ImplicitGlobalGrid.jl`](https://github.com/eth-cscs/ImplicitGlobalGrid.jl). Otherwise, it will define the wrong geometry when using multiple processes.

2023-05-02 13:04 UTC, merged