Compute local rank grid with `lazy_grid`
PTsolvers/JustRelax.jl pull request #85
Opened 2023-12-28 15:25 UTC by albert-de-montserrat

2023-12-28 15:33 UTC, boriskaus commented
`lazy_grid` and friends are routines that are useful also outside `JustRelax`. Would it make sense to put that in a different package (e.g., `CompGrids`)?

2023-12-28 15:47 UTC, albert-de-montserrat commented
It would makes sense. What's the state of `CompGrids`? is it usable or needs a good update/rework?

2023-12-28 15:51 UTC, boriskaus commented
it essentially contains nothing, so adding `lazy_grid` here as well as the `CreateArrays` function we discussed on Discord would be a great start. 
It would allow us to make `GeophysicalModelGenerator` compatible with `ParallelStencil` examples with a rather minor changes.

2023-12-28 16:01 UTC, albert-de-montserrat commented
Cool! Once I have everything fully figured out and tested in JR I will see how to move it out with a proper API. `CompGrids` can be a starting point.

2024-01-02 15:44 UTC, boriskaus commented
Can `heatdiffusion_PT!` deal with nonlinearities caused by latent heat? 
If yes, it could fully replace the corresponding routine in `MagmaThermoKinematics` (with the advantage that `JustRelax` runs with MPI as well).

2024-01-02 16:27 UTC, albert-de-montserrat commented
Not in the current state, but it should be just some extra lines of code. I
will add it as soon as I can. Anything else needed for MTK?

On Tue, 2 Jan 2024, 16:44 Boris Kaus, ***@***.***> wrote:

> Can heatdiffusion_PT! deal with nonlinearities caused by latent heat?
> If yes, it could fully replace the corresponding routine in
> MagmaThermoKinematics (with the advantage that JustRelax runs with MPI as
> well).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PTsolvers/JustRelax.jl/pull/85#issuecomment-1874193272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN23AHGVMOCMPBE2AAZNF4TYMQTN7AVCNFSM6AAAAABBFT5DPOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZUGE4TGMRXGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-10 13:56 UTC, aelligp requested changes
looks good, just some minor typos/suggestions

2024-01-10 13:56 UTC, aelligp commented on miniapps/benchmarks/stokes2D/shear_band/ShearBand2D_MPI.jl
> +    IGG(init_global_grid(nx, ny, 1; init_MPI = true)...)
```suggestion
    IGG(init_global_grid(nx, ny, 1; init_MPI = true, select_device=false)...)
```

2024-01-10 13:56 UTC, aelligp commented on miniapps/benchmarks/stokes2D/VanKeken.jl/VanKeken.jl
>  else
```suggestion
else
       model = PS_Setup(:cpu,  Float64, 2)
```

2024-01-10 13:56 UTC, aelligp commented on miniapps/benchmarks/stokes3D/shear_heating/Shearheating3D.jl
> +model = PS_Setup(:CUDA, Float64, 3)
```suggestion
model = PS_Setup(:cpu, Float64, 3)
```

2024-01-10 13:56 UTC, aelligp commented on miniapps/benchmarks/stokes3D/shear_heating/Shearheating3D.jl
> +n        = 64
```suggestion
n        = 16
```

2024-01-10 13:56 UTC, aelligp commented on miniapps/convection/Particles2D/Layered_convection2D.jl
> +model = PS_Setup(:Threads, Float64, 2)
```suggestion
model = PS_Setup(:cpu, Float64, 2)
```

2024-01-10 13:56 UTC, aelligp commented on miniapps/convection/Particles3D/Layered_convection3D.jl
> +            slice_j = Int(ny ÷ 2)
```suggestion
            slice_j = ny >>> 1
```

revert back to original notation

2024-01-10 15:07 UTC, aelligp approved these changes

2024-01-10 15:38 UTC, merged